# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: stator CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.13.1]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Increase watcher limit
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Inject Nx Cloud token
        shell: bash
        env:
          nx_cloud_token: ${{ secrets.NX_CLOUD_TOKEN }}
        run:
          sed -i "s/nx_cloud_token/$nx_cloud_token/" $GITHUB_WORKSPACE/nx.json

      - name: Setup postgres container
        run: docker-compose -f $GITHUB_WORKSPACE/apps/database/postgres/docker-compose.yml up -d

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        run: npm i

      - name: Lint files
        run: npm run affected:lint -- --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }}

      - name: Enforce naming conventions
        run: npm run lint:file-folder-convention

      - name: Build affected apps
        run: npm run affected:build -- --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }}

      - name: Start api
        run: npm run typeorm -- migration:run && npm start api &

      - name: Run tests
        run: npm run affected:test -- --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --code-coverage

      - name: Run e2e tests
        run: npm run affected:e2e -- --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ./coverage/apps/api/lcov.info
        continue-on-error: true

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/apps/api/
        continue-on-error: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release
